insert into specialities(name)
values ('English'),
       ('Biology'),
       ('Drawing'),
       ('Chemistry'),
       ('Choreography'),
       ('Design'),
       ('Physics'),
       ('Geography'),
       ('Information technologies'),
       ('Spanish'),
       ('History'),
       ('Italian'),
       ('Maths'),
       ('Music'),
       ('French'),
       ('Psychology'),
       ('German'),
       ('Lithuanian'),
       ('Polish'),
       ('Other');
